### ISSUE TITLE
broken sym links (vagrant box)

### ISSUE THREAD

**Issue by elix0r** [julieeen/kleefl#1]
Hello, 

I am trying to set up kleefl based on the readme, however I am stuck once I hit the build step. I was able to run the kleefl_init script just fine to create the needed directories but kleefl_build seems to run into issues with a broken symbolic link. See output below:

```
~/tests #! ls -la /home/vagrant/tools 
total 8
drwxrwxr-x  2 vagrant vagrant 4096 Mar  4  2016 .
drwxr-xr-x 18 vagrant vagrant 4096 Sep  5 15:44 ..
lrwxrwxrwx  1 root    root      23 Mar  3  2016 KTest.py -> /vagrant/tools/KTest.py
lrwxrwxrwx  1 root    root      24 Mar  3  2016 KTest.pyc -> /vagrant/tools/KTest.pyc
lrwxrwxrwx  1 root    root      27 Mar  3  2016 kleefl_build -> /vagrant/tools/kleefl_build
lrwxrwxrwx  1 root    root      26 Mar  3  2016 kleefl_init -> /vagrant/tools/kleefl_init
lrwxrwxrwx  1 root    root      26 Mar  3  2016 kleefl_pick -> /vagrant/tools/kleefl_pick
lrwxrwxrwx  1 root    root      33 Mar  3  2016 kleefl_prepare_afl -> /vagrant/tools/kleefl_prepare_afl
lrwxrwxrwx  1 root    root      25 Mar  3  2016 run_afl.sh -> /vagrant/tools/run_afl.sh
lrwxrwxrwx  1 root    root      26 Mar  3  2016 run_klee.sh -> /vagrant/tools/run_klee.sh

~/tests #! ls -la /vagrant/tools 
total 84
drwxr-xr-x 1 vagrant vagrant  4096 Aug 30 18:11 .
drwxr-xr-x 1 vagrant vagrant  4096 Sep  5 15:26 ..
-rw-r--r-- 1 vagrant vagrant  1739 Aug 30 18:11 KTest.py
-rwxr-xr-x 1 vagrant vagrant  1794 Aug 30 18:11 kleefl_build_cmake
-rwxr-xr-x 1 vagrant vagrant  1933 Aug 30 18:11 kleefl_build_make
-rwxr-xr-x 1 vagrant vagrant  3508 Aug 30 18:11 kleefl_cov_inspector
-rwxr-xr-x 1 vagrant vagrant 15007 Aug 30 18:11 kleefl_crash_inspector
-rwxr-xr-x 1 vagrant vagrant  1268 Sep  5 15:23 kleefl_init
-rwxr-xr-x 1 vagrant vagrant    91 Aug 30 18:11 kleefl_inspect_afl
-rwxr-xr-x 1 vagrant vagrant   634 Aug 30 18:11 kleefl_pick
-rwxr-xr-x 1 vagrant vagrant 11640 Aug 30 18:11 kleefl_prepare_afl
drwxr-xr-x 1 vagrant vagrant  4096 Aug 30 18:11 other
-rwxr-xr-x 1 vagrant vagrant    12 Aug 30 18:11 run_afl.sh
-rwxr-xr-x 1 vagrant vagrant   539 Aug 30 18:11 run_klee.sh
-rwxr-xr-x 1 vagrant vagrant  5950 Aug 30 18:11 show_klee_results
```

**Comment by julieeen** [comment]
Hi! Could you please paste the output of kleefl_build? The dir structure looks fine so far.

**Comment by elix0r** [comment]
Thanks for the reply! 
 
Output of running `python /home/vagrant/tools/kleefl_build make`
`python3: can't open file '/home/vagrant/tools/kleefl_build': [Errno 2] No such file or directory`

Heres the file command showing the broken sym link 
`/home/vagrant/tools/kleefl_build: broken symbolic link to /vagrant/tools/kleefl_build`

As you can see kleefl_build is not within the /vagrant/tools/ directory listed above. Could this be due to any errors on my end configuring the vagrant box?

**Comment by julieeen** [comment]
Oh! Thats easy: use kleefl_build_make (or kleefl_build_cmake)
If you have trouble building your targets have a look at the script itself - it's pretty simple.

**Comment by elix0r** [comment]
Ahh okay I thought you wanted me to run kleefl_build instead! Thanks I'll run the make/cmake version :).

**Comment by elix0r** [comment]
Closing issue as I was able to build with kleefl_build_make. Added changes.
