### ISSUE TITLE
Error on Build source using wllvm & afl-clang

### ISSUE THREAD

**Issue by ikhwan12** [julieeen/kleefl#5]
Hi ! I am so interest with your amazing work.
I wanna try to install your tool on my PC. I have followed all the instructions. Unfortunately, I got stuck on build source using wllvm & afl-clang. I got the error like this :

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Usage: kleefl_build_make [OPTION]

Option 			Meaning
make 			will make afl and klee options
make asan 		will make afl-asan and klee options
make afl 		will make afl instrumented binary
make cov		will make gcov of binary
make afl-asan		will make optional afl Asan instrumented binary
clean			will clean all builds
clean afl 		will clean afl build
clean cov 		will clean gcov build of binary
clean afl-asan		will clean afl Asan binary
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Step 2: Creating executable with AFL compiler afl-clang and afl-clang++
afl_build
../../kleefl/tools/kleefl_build_make: line 31: ../configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
/home/vagrant/project_xyz/source
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Step 3: Building wllvm
../../kleefl/tools/kleefl_build_make: line 67: ../configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
trying to create bitcode from '.' (when executable)
ERROR:File "." of type UNKNOWN cannot be used

I don't understand why did it happen ? I will be so happy if you want to explain it to me ?
Thank you very much

**Comment by julieeen** [comment]
Hi, seems like there is no makefile in the project you are trying to build.
First of all you should try to build the application without kleefl_build_make as normal.
When this works, you can make use of our build wrapper.

**Comment by bshastry** [comment]
Hey @ikhwan12 Can you please close issue if problem is fixed? Thanks.

**Comment by ikhwan12** [comment]
Hi @julieeen thank you for your answer. I am sorry for late response.
Yes, the problem is fixed. But, I got another issue.

Should I close this and create a new issue to discuss it?
Thank you.
